version: '3.8'

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: pcs
      POSTGRES_USER: pcs-user
      POSTGRES_PASSWORD: GjE7tS5wa5C73f
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: