openapi: 3.0.0
info:
  title: PCS API
  description: Spécification API du PCS
  version: 1.0.0
tags:
  - name: user
    description: Inscription au PCS

paths:
  /api/user:
    get:
      summary: Récupérer les informations d'utilisateur
      description: Récupère les informations d'utilisateur.
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                username: john_doe
                email: john@example.com
    post:
      summary: Enregistrer un nouvel utilisateur
      description: Permet à un utilisateur de s'enregistrer sur le PCS
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            example:
              username: john_doe
              password: mypassword123
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: Utilisateur enregistré avec succès
        '400':
          description: Requête incorrecte
          content:
            application/json:
              example:
                error: Erreur de validation
    delete:
      summary: Supprimer un utilisateur
      description: Supprime un utilisateur du PCS
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: Utilisateur supprimé avec succès
    put:
      summary: Mettre à jour les informations d'un utilisateur
      description: Met à jour les informations d'enregistrement d'un utilisateur sur le PCS
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            example:
              username: john_doe
              password: mynewpassword456
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: Informations utilisateur mises à jour avec succès
        '400':
          description: Requête incorrecte
          content:
            application/json:
              example:
                error: Erreur de validation
